### ISSUE TITLE
Cross validation guide

### ISSUE THREAD

**Issue by Priyansi** [pytorch-ignite/examples#28]
Ideas on how to do cross-validation: https://github.com/pytorch/ignite/issues/1384

**Comment by LiviaCavalcanti** [comment]
Hi! Is it ok to use scikit-learn’s k-fold functionality to split the data?

**Comment by vfdev-5** [comment]
@LiviaCavalcanti yes, sure!

**Comment by Priyansi** [comment]
Hey @LiviaCavalcanti , I started working on this notebook last week. It's a basic code sample. It still needs some explanation and a bit of restructuring. Do you want to work on [this notebook](https://colab.research.google.com/drive/10PUu7QVCYfp788Mq7rIBj8lfr-ox-8FT?usp=sharing) and send a PR for this?

For ideas on how to add explanation: refer to https://pytorch-ignite.ai/how-to-guides/

Please feel free to ask any more questions!

**Comment by LiviaCavalcanti** [comment]
Wow you've done all the hard work. I would be glad to work on the explanation! I will send the PR with it.

**Comment by Priyansi** [comment]
Thank you @LiviaCavalcanti ! BTW, the code is just an example. If you feel like it can be simplified, feel free to make changes there too :)
