### ISSUE TITLE
Add weight in frontmatter

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/examples#30]
Add `weight` in frontmatter of how to guides and tutorials pages. It could allow Hugo to sort the order of appearance.

See: https://gohugo.io/templates/lists#by-weight

TLDR; Lower number get higher precedence. So we shall start with 1. And I suggest to rename the file names to start with number like `01-file-name` or `1-file-name` so that it will show in order when viewing. And it could allow to scan the files.
It also allow us to see the files in order in the sidebar on the website.

For example:

```
01-installation
02-data-iterator
03-gradient-accumulation
04-fastai-lr-finder
05-time-profiling
...
```

cc @Priyansi @vfdev-5

**Comment by Priyansi** [comment]
So just something like:
```
title: How to install PyTorch-Ignite
date: 2021-08-04
weight: 1
downloads: true
sidebar: true
summary: Install PyTorch-Ignite from pip, conda, source or use pre-built docker images
tags:
  - installation
```

**Comment by ydcjeff** [comment]
Yes, like that.
