### ISSUE TITLE
could you give an example of how to save checkpoints?

### ISSUE THREAD

**Issue by tomisalready** [pytorch-ignite/examples#47]
unfortunately, as i upgrade the ignite, i don't know how to save my model's checkpoints, becuase the save_interval is deprecated,  my code is below, but it doesn' work.
`
checkpointer = ModelCheckpoint(output_dir, cfg.MODEL.NAME, n_saved=10, require_empty=False)
trainer.add_event_handler(Events.EPOCH_COMPLETED(every=1), checkpointer, to_save={'model': model,
                                                                     'optimizer': optimizer})
`

please give an example, thanks

**Comment by tomisalready** [comment]
i install the pytorch-ignite 0.4.6, but save_interval is deprecated in this version, i want save my trainning checkpoints, there's no example of how to save this. could you offer an example? thanks

**Comment by vfdev-5** [comment]
Please check out the docs and tutorials:
- https://pytorch.org/ignite/generated/ignite.handlers.checkpoint.ModelCheckpoint.html#ignite.handlers.checkpoint.ModelCheckpoint
- https://pytorch-ignite.ai/tutorials/getting-started/
