### ISSUE TITLE
Replace all instances of `save_handler=DiskSaver(...)` with `save_handler=path/to/dir`

### ISSUE THREAD

**Issue by Priyansi** [pytorch-ignite/examples#53]
Since PyTorch-Ignite v0.4.7, we have updated `save_handler` in [`Checkpoint`](https://pytorch.org/ignite/generated/ignite.handlers.checkpoint.Checkpoint.html#checkpoint) to pass the path to checkpoint directory rather than mentioning `DiskSaver(checkpoint_dir, create_dir=True)`. It would be nice if this could be updated for all instances in this repository too. One such instance can be in under [Checkpointing in How to convert PyTorch Code to Ignite](https://pytorch-ignite.ai/how-to-guides/02-convert-pytorch-to-ignite/#checkpointing).

**Comment by anirudhb11** [comment]
@Priyansi could you please assign this to me?

**Comment by sdesrozis** [comment]
@anirudhb11 Thank you for your interest !

**Comment by Priyansi** [comment]
Hey @anirudhb11 , any updates on this?

**Comment by anirudhb11** [comment]
@Priyansi am a bit occupied with some other engagements, I will raise a PR positively by Sunday.

**Comment by Priyansi** [comment]
@anirudhb11 Thanks!
