### ISSUE TITLE
Split for summary

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/examples#8]
Hugo has built-in ability to split for summary from the markdown files.

Add `<!--more-->` (should be exact) where you want to show the summary as the content before `<!--more-->`.

OR

Add `summary` frontmatter if the summary doesn't look good from markdown content.

Link to [`<!--more-->`](https://gohugo.io/content-management/summaries/#manual-summary-splitting)

[Example](https://raw.githubusercontent.com/pytorch-ignite/pytorch-ignite.github.io/main/content/posts/2020-09-pytorch-ignite.md?token=AHZWBFB6D4AJ4AUFCIC5OLTBAAM7M)

This could allow the summary to be shown consistently on the website.

cc @Priyansi

**Comment by vfdev-5** [comment]
@ydcjeff can we close this issue or it is still relevant ?
