### ISSUE TITLE
Update `01-collective-communication` notebook regarding NCCL `gather` support

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch-ignite/examples#81]
NCCL now supports `gather` operator. The line in bottom should be updated.
https://github.com/pytorch-ignite/examples/blob/c2657d3d7c189fa0b1c2f3f8cc16d2d948b2e7b2/tutorials/advanced/01-collective-communication.ipynb?short_path=30012cd#L307

**Comment by vfdev-5** [comment]
@sadra-barikbin can you share the nccl version supporting that or a link on pytorch docs where this is visible ?

**Comment by sadra-barikbin** [comment]
Oh I forgot that. https://pytorch.org/docs/stable/distributed.html#backends
