### ISSUE TITLE
python files besides notebook

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/examples#9]
Currently, the download links for python files are not working.
https://pytorch-ignite.ai/tutorials/getting-started/

Because there is no python files in this repo which is used as submodule in the website repo.

It would be great if python files are also in this repo to ease the download of python files.

cc @Priyansi @trsvchn @vfdev-5

**Comment by vfdev-5** [comment]
@ydcjeff can't we automatically generate python files from ipynb ?

**Comment by ydcjeff** [comment]
> @ydcjeff can't we automatically generate python files from ipynb ?

I think we can, but that will make changes to the submodule.

**Comment by vfdev-5** [comment]
I was thinking about on-fly generation when the download button is pressed. However, there will be a question where to store generated file etc. I think we can just remove download python files for simplicity ... What do you think ?

**Comment by ydcjeff** [comment]
We need to generate beforehand to download. I will remove download python files button.
